---
title: "Crossfitting example"
format:
  html:
    toc: true
    embed-resources: true
editor: source
---

## Introduction

Simple crossfitting example

```{r message=FALSE}
library(caret)
library(sjPlot)
```

Any parameters go here:

- `k`: number of folds
- `n_samples`: number of samples

```{r}
k_folds = 5
n_samples = 10000
```


# One confounder, one treatment

## Data

```{r}
x1 = rnorm(n_samples, mean = 0, sd = 1)

x1_t = 2

t = x1 * x1_t + rnorm(n_samples, 0, 0.5)

plot(x1, t)

x1_y = 1.5
t_y = 2.5

y = x1 * x1_y + t * t_y + rnorm(n_samples, 0, 0.25)

plot(x1, y)
plot(t, y)

df = data.frame(x1, t, y)
```

## Classic causal model

```{r}
mod_lm = lm(y ~ t + x1, df)
tab_model(mod_lm)
```

## FWL method with cross-fitting

```{r}
folds <- createFolds(df$y, k = k_folds)

df$t_hat = df$y_hat = NA

for (k in 1:k_folds) {
  ## Split data
  df_train = df[-folds[[k]], ]
  df_test = df[folds[[k]], ]

  ## Propensity model
  mod = lm(t ~ x1, df_train)
  df$t_hat[folds[[k]]] = predict(mod, newdata = df_test)
  
  ## Outcome model
  mod = lm(y ~ x1, df_train)
  df$y_hat[folds[[k]]] = predict(mod, newdata = df_test)

}

df$t_res = df$t - df$t_hat
df$y_res = df$y - df$y_hat

```



```{r}
## Final model
mod_final = lm(y_res ~ t_res - 1, df) ## Remove intercept
tab_model(mod_final)
```

