---
title: "Crossfit with random forest"
format:
  html:
    toc: true
    embed-resources: true
editor: source
---

## Data


```{r message=FALSE, warning=FALSE}
library(ranger)
library(caret)
library(sjPlot)
library(pdp)
```

```{r}
set.seed(42)
N <- 10000
p <- 10
X <- matrix(rnorm(N * p), N, p)
colnames(X) <- paste0("X", 1:p)

# Confounders influence both the treatment (D) and the outcome (Y)
g_X <- sin(X[, 1]) + exp(X[, 2])
m_X <- X[, 1]^2 + X[, 3]

# True treatment effect (CATE / ATE)
t_y = 2.5
t <- rbinom(N, 1, plogis(m_X))
y <- t_y * t + g_X + rnorm(N)

# Combine into a data frame
df <- data.frame(y = y, t = t, X)
```

```{r}
head(df)
```

```{r}
ggplot(df, aes(x = X1, y = t)) + 
  geom_point() + 
  geom_smooth()
```

```{r}
ggplot(df, aes(x = X1, y = y)) + 
  geom_point() + 
  geom_smooth()
```

## FWL method with cross-fitting

```{r}
k_folds <- 5  # Number of folds
folds <- createFolds(df$y, k = k_folds)

df$t_hat = df$y_hat = NA

for (k in 1:k_folds) {
  df_train = df[-folds[[k]], ]
  df_test = df[folds[[k]], ]

  ## Propensity model
  mod_t <- ranger(t ~ ., data = df_train[, c("t", colnames(X))])
  df$t_hat[folds[[k]]] = predict(mod_t, data = df_test[, colnames(X)])$predictions

  ## Outcome model
  mod_y <- ranger(y ~ ., data = df_train[, c("y", colnames(X))])
  df$y_hat[folds[[k]]] = predict(mod_y, data = df_test[, colnames(X)])$predictions

}

df$t_res = df$t - df$t_hat
df$y_res = df$y - df$y_hat

```

### Partial plot

```{r}

par_df = partial(mod_t, pred.var = "X1")
ggplot(par_df, aes(x = X1, y = yhat)) +
  geom_line() +
  theme_bw()

```

```{r}

par_df = partial(mod_y, pred.var = "X1")
ggplot(par_df, aes(x = X1, y = yhat)) +
  geom_line() +
  theme_bw()

```

## Final model

```{r}
## Final model
mod_final = lm(y_res ~ t_res - 1, df)
tab_model(mod_final)
```

